-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
SELECT COUNT(*) AS total_orders
FROM SALES s
JOIN CUSTOMERS c ON s.Customer_id = c.Customer_id
WHERE s.Date = '2023-03-18'
  AND c.First_name = 'John'
  AND c.Last_name = 'Doe';

-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT COUNT(DISTINCT Customer_id) AS total_customers,
       AVG(total_spent) AS avg_amount_spent
FROM (
    SELECT Customer_id, SUM(Revenue) AS total_spent
    FROM SALES
    WHERE Date BETWEEN '2023-01-01' AND '2023-01-31'
    GROUP BY Customer_id
) AS customer_spending;

-- Pull the departments that generated less than $600 in 2022
SELECT i.Department, SUM(s.Revenue) AS total_revenue
FROM SALES s
JOIN ITEMS i ON s.Item_id = i.Item_id
WHERE s.Date BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY i.Department
HAVING total_revenue < 600;

-- What is the most and least revenue we have generated by an order
SELECT MAX(Revenue) AS most_revenue,
       MIN(Revenue) AS least_revenue
FROM SALES;

-- What were the orders that were purchased in our most lucrative order
WITH MaxRevenue AS (
    SELECT MAX(Revenue) AS max_revenue
    FROM SALES
)

SELECT *
FROM SALES
WHERE Revenue = (SELECT max_revenue FROM MaxRevenue);